### ISSUE TITLE
neutron/ml2.sls fails when run twice

### ISSUE THREAD

**Issue by arthurzenika** [CSSCorp/openstack-automation#18]
The following step in neutron/ml2.sls fails when run twice

```
----------
          ID: intergrationg_bridge
    Function: cmd.run
        Name: ovs-vsctl add-br br-int
      Result: False
     Comment: Command "ovs-vsctl add-br br-int" run
     Changes:   
              ----------
              pid:
                  16413
              retcode:
                  1
              stderr:
                  ovs-vsctl: cannot create a bridge named br-int because a bridge named br-int already exists
              stdout:
```

It should check if the bridge is already configured (and configured according to the spec) and not do anything if it is.
